coverage_service: cobertura_xml
xcodeproj: Sample/SampleForageSDK.xcodeproj
scheme: ForageSDK
ignore:
  - ../Library/*
  - ../../Library/*
  - ../../../Library/*
  - "**/Vendor/DatadogCore/*"
  - "**/Vendor/DatadogInternal/*"
  - "**/Vendor/DatadogLogs/*"
  - "DatadogPrivate-Objc/*"
  - "**/DatadogPrivate-Objc/*"
  - "Sources/ForageSDK/Foundation/Telemetry/NoopLogger.swift"
  - "**/Sources/ForageSDK/Foundation/Telemetry/NoopLogger.swift"
  - Tests/*
