name: Alert

on:
  workflow_run:
    workflows: ["QA Tests"]
    types: ["completed"]
    branches: ["main"]

jobs:
  send-alert:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Send alert to slack
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "message": "QA Tests failed on main branch in forage-ios-sdk! https://github.com/teamforage/forage-ios-sdk/actions"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
