name: PR Validations

on: [pull_request]

jobs:
  pod-linting:
    name: Pod Linting
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        # v6.0.2 = de0fac2e4500dabe0009e67214ff5f5447ce83dd
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      
      - name: Pod Linting
        run: pod lib lint --allow-warnings
