name: PR Validations

on: [pull_request]

jobs:
  pod-linting:
    name: Pod Linting
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Pod Linting
        run: pod lib lint --allow-warnings
